[package]
name = "bus-vis"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tui = "0.17"
crossterm = "0.22"
reqwest = { version = "0.11", features = ["json", "blocking"] }
serde_json = "1.0"